domain: "mysterypancake.github.io"
url: "https://mysterypancake.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Hallam Roberts" # the name of your site, e.g. ACME Corp.
description: "Visual effects, motion graphics, coding and music"
include:
  - _pages
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/
navigation:
  - title: Home
    url: /
  - title: Contact
    url: /contact